---
deployment:
    tasks:
        - rsync -avz --delete --include='.env' --exclude='static/' --exclude='.*' ./ ~/Ganga-Aarti/
        - rsync -avz --delete --exclude='.*' ./static/ ~/public_html/static/
