---
deployment:
    tasks:
        # Sync all files from the current directory to `Ganga-Aarti`, including `.env`, excluding `static` and hidden files
        - rsync -avz --delete --include='.env' --exclude='static/' --exclude='.*' ./ ~/Ganga-Aarti/

        # Sync files from the `static` directory to `public_html/static`
        - rsync -avz --delete --exclude='.*' ./static/ ~/public_html/static/
